[MEMBERS] model - migration - seeder - OT102-88
alkemyTech/OT102-Server pull request #10
Opened 2021-11-23 21:50 UTC by WernerBudtke

# [OT102-41](https://alkemy-labs.atlassian.net/browse/OT102-41)

# Description:
AS: administrator user
I WANT: to manage the members of the ONG
TO: modify the Members of the Organization

# Acceptance criteria: 
It will be possible to manage the members of the ONG. Name of the table: members. Fields: name, image

# How to reproduce this change:
apply migration:
`npx sequelize-cli db:migrate`
seed:
`npx sequelize-cli db:seed:all`
undo migration:
`npx sequelize-cli db:migrate:undo:all --to XXXXXXXXXXXXXX-nombre-migracion.js`

2021-11-23 22:03 UTC, joselo85 commented on migrations/20211123063059-create-member.js
> +      },
Al campo de name, le pondria: allowNull: false

2021-11-23 22:05 UTC, joselo85 commented on models/member.js
> +  });
Fijate que  hay q agregar lo siguiente: createdAt: 'created_at', updatedAt: 'updated_at', deletedAt: 'deletedAt',  paranoid: true,  timestamps: true,

2021-11-24 03:04 UTC, dvelezroman commented on seeders/20211123063059-create-members.js
> +      createdAt: new Date,
`createdAt: new Date()`

2021-11-24 03:05 UTC, dvelezroman requested changes
buen PR.. solo pequenios cambios solicitados

2021-11-24 03:05 UTC, dvelezroman commented on seeders/20211123063059-create-members.js
> +      updatedAt: new Date
`updatedAt: new Date()`

2021-11-24 14:22 UTC, gabyMangoni commented on package-lock.json
>  {
Ojo... esto no deberias mergearlo con develop.. a mi me paso lo mismo...

2021-11-24 21:31 UTC, dvelezroman approved these changes
Realizar los cambios y mergear...

2021-11-25 01:55 UTC, JonatanGarbuyo approved these changes

2021-11-25 14:10 UTC, joselo85 submitted a review, later dismissed

2021-11-25 14:15 UTC, joselo85 approved these changes

2021-11-25 16:10 UTC, merged