[CONTACT]: model - migration - seeder - OT102-71-2
alkemyTech/OT102-Server pull request #11
Opened 2021-11-23 23:42 UTC by gabyMangoni

https://alkemy-labs.atlassian.net/browse/OT102-71
-----------------------------------------------------------------------------------------------------------------------------------------

**Description:**
-----------------------------------------------------------------------------------------------------------------------------------------
AS: administrator user
I WANT: Store the data when completing the Contact Form
TO: Have a Contacts database

**Acceptance criteria:**
-----------------------------------------------------------------------------------------------------------------------------------------
By completing the Contact Form, it will be stored in the database. Table name: contacts. It will contain the fields name, phone, email, message, deletedAt (used for soft delete)

**How to reproduce this change:**
-----------------------------------------------------------------------------------------------------------------------------------------
apply migration:
npx sequelize-cli db:migrate

undo migration:
npx sequelize-cli db:migrate:undo:all --to XXXXXXXXXXXXXX-nombre-migracion.js

2021-11-23 23:44 UTC, dvelezroman commented on migrations/20211122231452-create-contact.js
> +        type: Sequelize.INTEGER,
phone debe ser un STRING

2021-11-23 23:45 UTC, dvelezroman requested changes
Solo un pequeno cambio en el tipo de phone

2021-11-23 23:45 UTC, dvelezroman commented on models/contact.js
> +    phone: DataTypes.INTEGER,
phone  debe ser STRING

2021-11-24 03:06 UTC, dvelezroman approved these changes
Excelente

2021-11-24 12:25 UTC, JonatanGarbuyo approved these changes

2021-11-24 12:29 UTC, gabodmc approved these changes

2021-11-24 14:16 UTC, alexiscjscab approved these changes

2021-11-24 14:57 UTC, merged