[MIDDLEWARE] isAdmin -OT102-52
alkemyTech/OT102-Server pull request #25
Opened 2021-11-26 15:47 UTC by maxicuyo94

HOW: admin user
I WANT: restrict access to certain content
TO: keep data safe

Acceptance criteria: You must verify the roleId field, and allow to continue if the user has a role corresponding to administrator

I use jwt and attached examples to use it and to call it
![image](https://user-images.githubusercontent.com/76572701/143604960-61fa9d9b-8b11-46c1-8851-f76c6fb22ecb.png)

2021-11-26 18:27 UTC, dvelezroman commented on config/config.js
> +    secret: process.env.JWT_SECRET_KEY,
good

2021-11-26 18:32 UTC, dvelezroman requested changes
Good PR .... few comments.

2021-11-26 18:32 UTC, dvelezroman commented on middlewares/isAdmin.js
> +    return res.status(401).send({ auth: false, message: 'No token provided.' })
apply the error handler here...

2021-11-26 18:32 UTC, dvelezroman commented on middlewares/isAdmin.js
> +        .status(500)
error handler here as well

2021-11-26 18:32 UTC, dvelezroman commented on middlewares/isAdmin.js
> +        .send({ auth: false, message: 'Failed to authenticate token.' })
use .json

2021-11-26 18:32 UTC, dvelezroman commented on middlewares/isAdmin.js
> +    if (decoded.roleId === 1) {
what if Admin has another roleId ???  we should assure to compare with the role name.

2021-11-26 18:32 UTC, dvelezroman commented on middlewares/isAdmin.js
> +        .status(403)
same as above.. errorhandler

2021-11-26 18:32 UTC, dvelezroman commented on middlewares/isAdmin.js
> +        .send({ auth: false, message: 'You are not an admin' })
.json

2021-11-26 18:32 UTC, dvelezroman commented on middlewares/isAdmin.js
> +// examples
instead of this commented code... you could do : 
a document of this is README.md

2021-11-26 18:32 UTC, dvelezroman commented on routes/ping.js
> +router.get('/admin', isAdmin, pong)
this route is only for testing purposes.. to see if the sever is online... please do not use middleware for admin access here...

2021-11-27 14:51 UTC, maxicuyo94 commented
fixed requested

2021-11-28 05:40 UTC, JonatanGarbuyo reviewed
esta muy bien. te dejo algunos comentarios

2021-11-28 05:40 UTC, JonatanGarbuyo commented on middlewares/isAdmin.js
> +    next(new ErrorObject('No token provided.', 401))
si pasas el error con next no se devuelve correctamente
hay que devolver con res.json()

fijate en el  middleware de validateRequest

2021-11-28 05:40 UTC, JonatanGarbuyo commented on middlewares/isAdmin.js
> +      next(new ErrorObject('You are not an admin', 403))
devolver json() idem anterior.
ademas, solo debería devolver 'Forbiden' sin develar el funcionamiento interno.

2021-11-28 05:40 UTC, JonatanGarbuyo commented on middlewares/isAdmin.js
> +      next(new ErrorObject('Failed to authenticate token.', 401))
devolver con res.json()

2021-11-28 20:24 UTC, dvelezroman requested changes

2021-11-28 20:24 UTC, dvelezroman commented on middlewares/isAdmin.js
> +    next(new ErrorObject('No token provided.', 401))
con las modificaciones al error handler .. esto cambia... fijarse en la rama develop y el controller de user .

2021-11-29 18:11 UTC, JonatanGarbuyo approved these changes

2021-11-29 18:11 UTC, JonatanGarbuyo commented on middlewares/isAdmin.js
> +  }
te faltó usar el  createHttpError.  por ej:

const httpError = createHttpError( 401,  `[ No token provided. ] - [ ${req.baseUrl} - ${req.method}]`,  )
next(httpError)

sino'  tira mal el statusCode

2021-11-29 19:54 UTC, dvelezroman approved these changes

2021-11-29 20:23 UTC, gabodmc approved these changes

2021-11-29 20:23 UTC, gabyMangoni approved these changes
Approve

2021-11-29 21:04 UTC, merged