[ENDPOINT] PUT /testimonials/:id - OT102-85
alkemyTech/OT102-Server pull request #29
Opened 2021-11-26 22:38 UTC by joselo85

# Description:

AS: User Administrator
I WANT: To update "Testimonios"(Testimonials)
TO: Be able to inform about the NGO's new "Novedades"(News).

## Acceptance Criteria:

PUT request to  /testimonials/:id - Should validate the that the testimonial entry exists, based on the ID sent as a parameter. In case it doesn't exists, it should return an error, otherwise the entry should be updated and returned with the new data.

## Evidence:
### Table prior update request:
![DB 1](https://user-images.githubusercontent.com/74208929/143659229-5fdd3de5-0e7b-4077-a9f4-4a8e236c0244.png)
***

### Testimonial not found error:
![postman notfound](https://user-images.githubusercontent.com/74208929/143659267-601db62f-8d09-43b2-affa-6d170dfc1543.png)
***

### Succesful update:
![DB 2after](https://user-images.githubusercontent.com/74208929/143659296-8a4220ea-1c41-4504-92e3-a7ea7e384eaa.png)
***
![postman success](https://user-images.githubusercontent.com/74208929/143659308-cc7a31ad-7a80-4199-b831-9f2a49f686a3.png)

2021-11-28 05:34 UTC, JonatanGarbuyo reviewed
buen pr.  tenemos que probar errores también. no solo la happy route  :)

2021-11-28 05:34 UTC, JonatanGarbuyo commented on controllers/testimonials.js
> +        new ErrorObject(
si pasas el error con next no se devuelve correctamente
hay que devolver con res.json()

fijate en el controller de category.

2021-11-28 15:29 UTC, joselo85 commented on controllers/testimonials.js
> +        new ErrorObject(
Genial, ahora lo veo. Gracias!

2021-11-28 19:38 UTC, dvelezroman commented on controllers/testimonials.js
> +        new ErrorObject(
la response en error debera ser asi
`const httpError = createHttpError(404, `[Error deleting User] - [users - delete]: ${error.message}`)
      next(httpError)`

2021-11-28 20:54 UTC, dvelezroman requested changes
revisar como cambio el error hanlder con las modificaciones para que acepte el stack de errores de validacion y otros... revisar en la rama develop el controlador user

2021-11-29 19:56 UTC, dvelezroman commented on helpers/error.js
> +  constructor(message, statusCode, errors = []) {
muy buena ... funciona igual ?

2021-11-29 19:56 UTC, dvelezroman approved these changes

2021-11-29 20:24 UTC, gabodmc approved these changes

2021-11-29 20:25 UTC, maxicuyo94 approved these changes

2021-11-29 20:26 UTC, gabyMangoni approved these changes
Approve

2021-11-29 20:37 UTC, joselo85 commented on helpers/error.js
> +  constructor(message, statusCode, errors = []) {
Si, lo estuve probando varias veces y funciona.

2021-11-30 00:44 UTC, merged