add migration and categories model
alkemyTech/OT102-Server pull request #3
Opened 2021-11-23 00:50 UTC by JonatanGarbuyo

AS: administrator user
I WANT: to manage the Categories of the News
TO: correctly categorize the news

Acceptance criteria: The Categories will allow to classify entries. Table name to create: categories. Fields: name, description, deletedAt (used for softDelete)

2021-11-23 13:35 UTC, gabodmc approved these changes
All OK

2021-11-23 14:17 UTC, dvelezroman requested changes
Esta muy bueno el Pr.. solo unos comentarios...

2021-11-23 14:17 UTC, dvelezroman commented on .eslintrc.js
> +    'linebreak-style': [
veo este cambio en varios PRs... ponganse de acuerdo en cual PR se sube todo eso... para no pisarse unos con otros.

2021-11-23 14:17 UTC, dvelezroman commented on migrations/20211123004057-create-category.js
> +        allowNull: false,
no se si esto data problemas cuando insertes registro.... habra que ver en produccion

2021-11-23 14:17 UTC, dvelezroman commented on models/category.js
> +      modelName: 'Category',
agregar:
`createdAt: 'created_at',
  updatedAt: 'updated_at',
  deletedAt: 'deletedAt',
  paranoid: true,
  timestamps: true,`

2021-11-23 14:26 UTC, joselo85 commented on migrations/20211123004057-create-category.js
> +        allowNull: false,
En description, usas string, que seria hasta 255 caracteres. Alcanzara?

2021-11-23 15:03 UTC, JonatanGarbuyo commented on migrations/20211123004057-create-category.js
> +        allowNull: false,
Ah. bien pensado.
Es la cantidad  que puso por defecto.  cuanto le pongo?

2021-11-23 15:08 UTC, dvelezroman requested changes

2021-11-23 15:08 UTC, dvelezroman commented on migrations/20211123004057-create-category.js
> +        allowNull: false,
mejor usa tipo TEXT

2021-11-23 15:08 UTC, dvelezroman commented on migrations/20211123004057-create-category.js
> +        allowNull: false,
mejor usa tipo TEXT en el campo description

2021-11-23 21:59 UTC, joselo85 approved these changes

2021-11-24 02:47 UTC, dvelezroman approved these changes
bien

2021-11-24 12:58 UTC, merged

2021-11-24 13:02 UTC, maxicuyo94 reviewed
ok