[ENDPOINT] DELETE /news/:id - OT102-63
alkemyTech/OT102-Server pull request #33
Opened 2021-11-28 04:27 UTC by gabyMangoni

https://alkemy-labs.atlassian.net/browse/OT102-63

--------------------------------------------------------------------------------------------------------------------------------------------

**Description**
AS admin user
I WANT to delete an existing news
TO keep information up to date

--------------------------------------------------------------------------------------------------------------------------------------------

**Criteria of acceptance:**
DELETE / news /: id - It must validate the existence based on the id sent by parameter. If it exists, delete it

--------------------------------------------------------------------------------------------------------------------------------------------

**Evidence**

Get news/:2

![delete-1](https://user-images.githubusercontent.com/79479608/143729473-e293ab3b-f6d5-4562-900a-4be3f0975155.jpg)

Delete news/:2

![delete-2](https://user-images.githubusercontent.com/79479608/143729487-f5b4b115-01e2-47f8-8899-d72121507e32.jpg)

After - DeletedAt - MsSQL

![delete-3](https://user-images.githubusercontent.com/79479608/143729499-4c7865ed-5be2-439a-946a-a487955b736e.jpg)

2021-11-28 05:25 UTC, JonatanGarbuyo reviewed
bien gaby. te deje algunos coments.

2021-11-28 05:25 UTC, JonatanGarbuyo commented on controllers/entry.js
> +      next(new ErrorObject(`[Error deleting Entry] - [Entry - delete]: ${error.message}`, 500))
si pasas el error con next no se devuelve correctamente
hay que devolver con res.json()

fijate en el controller  de category.

2021-11-28 20:42 UTC, dvelezroman commented on controllers/entry.js
> +      next(new ErrorObject(`[Error deleting Entry] - [Entry - delete]: ${error.message}`, 500))
vale el comentario.. pero con las modificaciones al errorhandler.. ya no iria asi.... mirar como esta en la rama development en el controller de user

2021-11-28 20:42 UTC, dvelezroman requested changes
revisar las modificaciones que hubieron al error handler

2021-11-28 21:06 UTC, gabyMangoni commented on controllers/entry.js
> +      next(new ErrorObject(`[Error deleting Entry] - [Entry - delete]: ${error.message}`, 500))
Ahi estuve mirando el controller de user, pero con las modificaciones del errorhandler, hay que editar tambien el catch de get y getEntry (este ultimo lo hizo joselo).. no se si toco todo yo... o cada uno tiene que editar su parte?

2021-11-29 12:11 UTC, dvelezroman commented on controllers/entry.js
> +      next(new ErrorObject(`[Error deleting Entry] - [Entry - delete]: ${error.message}`, 500))
los endpoints que hizo cada uno deberian modificarlos con el manejo de error hanlder

2021-11-29 15:05 UTC, gabyMangoni commented on controllers/entry.js
> +      next(new ErrorObject(`[Error deleting Entry] - [Entry - delete]: ${error.message}`, 500))
Listo!

2021-11-29 19:57 UTC, dvelezroman approved these changes
Excellent

2021-11-29 20:15 UTC, joselo85 approved these changes

2021-11-29 20:24 UTC, gabodmc approved these changes

2021-11-29 20:41 UTC, alexiscjscab approved these changes

2021-11-29 21:09 UTC, dvelezroman requested changes

2021-11-29 21:09 UTC, dvelezroman commented on routes/entries.js
> +router.delete('/:id', destroy)
agregar middleware

2021-11-30 02:05 UTC, gabyMangoni commented on routes/entries.js
> +router.delete('/:id', destroy)
listo

2021-11-30 02:23 UTC, dvelezroman approved these changes
Excelente....con los fixes

2021-11-30 02:26 UTC, merged