[ENDPOINT]: POST /categories - OT102-97
alkemyTech/OT102-Server pull request #34
Opened 2021-11-28 04:57 UTC by JonatanGarbuyo

[OT102-97](https://alkemy-labs.atlassian.net/browse/OT102-97)
## Description:

AS admin user
I WANT to add a new category to the system
TO categorize the News

## Acceptance criteria:

POST / categories - You must validate that the name of the field is sent, and it is a string

## Evidence:

### field validation:
![val-name-err](https://user-images.githubusercontent.com/58077441/143730055-f99ebd19-eeab-4d5e-b69e-49bf4e37cc6d.png)

![val-description-err](https://user-images.githubusercontent.com/58077441/143730058-2d94937e-5e3b-4459-88c9-962e78412a9e.png)

#### create category 
![created](https://user-images.githubusercontent.com/58077441/143730067-46453c03-e822-489d-8882-5c2fdd3ecd1f.png)

#### errors
![dup-entry](https://user-images.githubusercontent.com/58077441/143730076-4f36fb20-0efe-49ef-be0b-a5ae1d5ac259.png)

![conn-error](https://user-images.githubusercontent.com/58077441/143730078-b2a5a9fc-bf6d-4186-8d3f-d0782ff44e87.png)

2021-11-28 15:25 UTC, joselo85 commented on services/categories.js
> +    return { id, name, description }
Te consulto, porque haces return del id, siendo que no lo usas para endpoint response?

2021-11-28 15:44 UTC, JonatanGarbuyo commented on services/categories.js
> +    return { id, name, description }
joselo. 
si que va en el response, está dentro de  body: newCategory
 lo desestructure  en el service para ver exactamente que es lo que devuelve.

2021-11-28 20:47 UTC, dvelezroman requested changes

2021-11-28 20:47 UTC, dvelezroman commented on services/categories.js
> +      throw new ErrorObject(
con la modificacion del error handler .. se manejaria a hora asi
`const httpError = createHttpError(500, '[Error retrieving users] - [users - get]: ${error.message}')
httpError.errors = error.errors
next(httpError)`

2021-11-29 15:23 UTC, gabodmc approved these changes
Todo perfecto. Solo me hacen ruido esos commits en el la ruta de categories (lineas 10, 12 y 14)

2021-11-29 15:25 UTC, gabyMangoni approved these changes
Approve!!!

2021-11-29 15:25 UTC, gabyMangoni approved these changes
Approve!!!

2021-11-29 19:58 UTC, dvelezroman approved these changes
Mergear este primero

2021-11-29 20:17 UTC, joselo85 approved these changes

2021-11-29 20:40 UTC, alexiscjscab approved these changes

2021-11-29 21:05 UTC, merged