[ENDPOINT]: GET /testimonials - OT102-121
alkemyTech/OT102-Server pull request #35
Opened 2021-11-28 16:21 UTC by JonatanGarbuyo

[OT102-121](https://alkemy-labs.atlassian.net/browse/OT102-121)
## Description:

AS user
I WANT to list the testimonials
TO be able to show them on the client

## Acceptance criteria:
GET / testimonials - Return testimonial records

## Evidence:
### field validation:

#### retrieve testimonials
![get-testimonials](https://user-images.githubusercontent.com/58077441/143776669-121b489f-ed30-4425-ae41-52896621a638.png)

#### retrieve testimonials error
![error](https://user-images.githubusercontent.com/58077441/143776675-e38c16b6-84be-4e48-8568-54caaf142553.png)

2021-11-28 20:50 UTC, dvelezroman commented on services/testimonials.js
> +    throw new ErrorObject(
`const httpError = createHttpError(500, `[Error retrieving users] - [users - get]: ${error.message}`)
     httpError.errors = [error]
      next(httpError)`

2021-11-28 20:50 UTC, dvelezroman requested changes
const httpError = createHttpError(500, `[Error retrieving users] - [users - get]: ${error.message}`)
      next(httpError)

2021-11-29 20:00 UTC, dvelezroman approved these changes

2021-11-29 20:16 UTC, gabyMangoni approved these changes
Approve

2021-11-29 20:38 UTC, joselo85 approved these changes

2021-11-29 21:06 UTC, merged