[ENDPOINT]: POST /members - OT102-90
alkemyTech/OT102-Server pull request #36
Opened 2021-11-28 18:33 UTC by JonatanGarbuyo

[OT102-90](https://alkemy-labs.atlassian.net/browse/OT102-90)
## Description:

AS user
I WANT to create a member
TO update the information on the web.

## Acceptance criteria:
POST / members - You must validate that the name field is sent, and it is a string

## Evidence:

### field validation:
![validate](https://user-images.githubusercontent.com/58077441/143781200-1e8aad9d-214f-4d6c-b1bf-78f8013caf43.png)

#### create member
![createMember](https://user-images.githubusercontent.com/58077441/143781209-e7cdba4d-52bc-4eb0-9636-cbfc1e3db5be.png)

#### errors handling
![con-error](https://user-images.githubusercontent.com/58077441/143781212-374ae93c-ac4a-4d6a-a839-0f3b6d98ea3c.png)

2021-11-28 20:52 UTC, dvelezroman requested changes

2021-11-28 20:52 UTC, dvelezroman commented on services/members.js
> +        error.errors,
`const httpError = createHttpError(500, `[Error retrieving users] - [users - get]: ${error.message}`)
      httpError.errors = errors
      next(httpError)`

2021-11-28 20:52 UTC, dvelezroman commented on services/members.js
> +    throw new ErrorObject(
`const httpError = createHttpError(500, [Error retrieving users] - [users - get]: ${error.message}) httpError.errors = errors next(httpError)`

2021-11-29 20:01 UTC, dvelezroman approved these changes
Buen PR

2021-11-29 20:17 UTC, gabyMangoni approved these changes
Approve

2021-11-29 20:24 UTC, gabodmc approved these changes

2021-11-30 00:58 UTC, merged