[ENDPOINT] DELETE /members/:id - OT102-92
alkemyTech/OT102-Server pull request #39
Opened 2021-11-29 19:32 UTC by gabodmc

[OT102-92](https://alkemy-labs.atlassian.net/browse/OT102-92)

**AS** user
I WANT delete a member
TO leave the organization

**Accepted criteria:** 
DELETE /members/:id - Must validate if it exists and remove it. If it doesn't, throw error.

### Evidence:
**Member list**

**Deleting member**
![1](https://user-images.githubusercontent.com/79473217/143930793-4b3f3b97-90ad-413b-ae08-07dacf66e703.png)
**Trying to delete a deleted member**
![2](https://user-images.githubusercontent.com/79473217/143930797-203d7db8-9167-4e6d-979f-74e30b2d85fc.png)
![3](https://user-images.githubusercontent.com/79473217/143930798-a9e91a4b-ff2e-4d11-aab9-50574fc5b6c7.png)

2021-11-29 20:02 UTC, dvelezroman commented on controllers/members.js
> +        new ErrorObject(
cambiar por el errorhandler actual

2021-11-29 20:02 UTC, dvelezroman requested changes
usar el nuevo formato de error handler...

2021-11-29 20:20 UTC, gabodmc commented on controllers/members.js
> +        new ErrorObject(
Hecho

2021-11-29 20:47 UTC, JonatanGarbuyo approved these changes

2021-11-30 02:22 UTC, dvelezroman approved these changes
Excelente

2021-11-30 12:28 UTC, gabyMangoni approved these changes
All Ok

2021-11-30 12:38 UTC, merged