Testimonials model/migrate
alkemyTech/OT102-Server pull request #4
Opened 2021-11-23 01:40 UTC by gabodmc

- Testimonials model and migration added
- Testimonial association with user model added

2021-11-23 12:52 UTC, JonatanGarbuyo reviewed
'name' y 'content'  deberían ser NOT NULL?

2021-11-23 14:13 UTC, gabodmc commented
> 'name' y 'content' deberían ser NOT NULL?

Ahi lo modifique. Gracias!

2021-11-23 14:19 UTC, dvelezroman commented
Arreglar el formato de la descripcion del PR como en PR [https://github.com/alkemyTech/OT102-Server/pull/3](https://github.com/alkemyTech/OT102-Server/pull/3)

2021-11-23 14:20 UTC, dvelezroman requested changes
Se ve bien solo unos cambios

2021-11-23 14:20 UTC, dvelezroman commented on models/testimonials.js
> +    modelName: 'Testimonials',
agregar configuracion como en los comentarios del PR
[https://github.com/alkemyTech/OT102-Server/pull/3](https://github.com/alkemyTech/OT102-Server/pull/3)

2021-11-23 14:40 UTC, gabodmc commented
> 



> Arreglar el formato de la descripcion del PR como en PR #3

Hecho!

2021-11-23 14:48 UTC, dvelezroman requested changes
Bien el PR.. solo poco cambios

2021-11-23 14:48 UTC, dvelezroman commented on migrations/20211123001017-create-testimonials.js
> +        type: Sequelize.STRING,
cambiar a tipo TEXT

2021-11-23 14:48 UTC, dvelezroman commented on migrations/20211123001017-create-testimonials.js
> +        paranoid:true,
eso no debe ir aqui ...  solo el `type: Sequelize.DATE`

2021-11-23 14:48 UTC, dvelezroman commented on models/testimonials.js
> +  class Testimonials extends Model {
usar singular: 
`class Testimonial extends Model {`

2021-11-23 14:48 UTC, dvelezroman commented on models/testimonials.js
> +    modelName: 'Testimonials',
en sigular Testimonial

2021-11-23 14:48 UTC, dvelezroman commented on models/testimonials.js
> +  return Testimonials;
en singular: `Testimonial`

2021-11-23 14:48 UTC, dvelezroman commented on models/testimonials.js
> +};
añadir una linea al final

2021-11-23 14:48 UTC, dvelezroman commented on migrations/20211123001017-create-testimonials.js
> +};
añadir una linea la final

2021-11-23 14:48 UTC, dvelezroman commented on migrations/20211123001017-create-testimonials.js
> +};
no usar ;

2021-11-23 14:53 UTC, dvelezroman requested changes

2021-11-23 14:53 UTC, dvelezroman commented on models/testimonials.js
> +    modelName: 'Testimonials',
singular

2021-11-23 16:54 UTC, JonatanGarbuyo approved these changes

2021-11-24 02:49 UTC, dvelezroman commented on models/testimonial.js
> +    image: DataTypes.STRING,
image es TEXT segun la migracion

2021-11-24 02:50 UTC, dvelezroman requested changes
solo un comentario

2021-11-24 11:56 UTC, gabodmc commented on models/testimonial.js
> +    image: DataTypes.STRING,
Hecho. Tambien modifiqué el text que estaba mal en la migración

2021-11-24 12:43 UTC, dvelezroman approved these changes
Antes de mergear cambiale el tipo de dato a name ... debe ser STRING.... de ahi esta bien lo demas

2021-11-24 12:43 UTC, dvelezroman commented on migrations/20211123145446-create-testimonial.js
> +        type: Sequelize.TEXT
name si deberia ser STRING

2021-11-24 12:43 UTC, dvelezroman commented on models/testimonial.js
> +    name: DataTypes.TEXT,
name deberia ser STRING

2021-11-24 12:49 UTC, gabodmc commented on migrations/20211123145446-create-testimonial.js
> +        type: Sequelize.TEXT
Corregido

2021-11-24 12:49 UTC, gabodmc commented on models/testimonial.js
> +    name: DataTypes.TEXT,
Corregido

2021-11-24 12:57 UTC, joselo85 approved these changes

2021-11-24 13:43 UTC, gabyMangoni approved these changes
All Ok

2021-11-24 14:31 UTC, merged