[ENDPOINT] POST / contacts Ot102-72
alkemyTech/OT102-Server pull request #46
Opened 2021-11-30 16:00 UTC by maxicuyo94

HOW: Developer
I WANT: Send the data of the Contact Form to the API
TO: Store them in the database

Acceptance criteria: POST / contacts - It will verify that the request contains the name and email fields

2021-11-30 20:45 UTC, dvelezroman requested changes
Buen PR.. solo deje un pequeño comentario para acomodar el errorhandler en un controller anterior...

2021-11-30 20:45 UTC, dvelezroman commented on controllers/contacts.js
> +      next(
esto cambiar por el nuevo manejador de error.. creo que se quedo del anterior

2021-11-30 21:04 UTC, JonatanGarbuyo approved these changes

2021-11-30 21:09 UTC, gabyMangoni approved these changes
Ok

2021-12-01 13:57 UTC, gabodmc approved these changes

2021-12-01 18:50 UTC, dvelezroman approved these changes
Good...

2021-12-01 20:53 UTC, Gabriiel99 approved these changes

2021-12-02 19:53 UTC, joselo85 approved these changes

2021-12-03 21:20 UTC, merged