migration-model-seeders of the activities table
alkemyTech/OT102-Server pull request #5
Opened 2021-11-23 06:55 UTC by Gabriiel99

To check that the database works use XAMPP and phpmyadmin.

2021-11-23 12:57 UTC, JonatanGarbuyo reviewed
en migrations 'name' es NOT NULL.  también debería estar en el Model.

'content' también debería ser NOT NULL

2021-11-23 14:21 UTC, dvelezroman commented
REvisar la descripcion del PR : [https://github.com/alkemyTech/OT102-Server/pull/3](https://github.com/alkemyTech/OT102-Server/pull/3) .... y completar la informacion

2021-11-23 14:26 UTC, dvelezroman requested changes
Buen Pr...solo unos cambios

2021-11-23 14:26 UTC, dvelezroman commented on models/activities.js
> +  class activities extends Model {
debe ser singular: 
`class Activity extends Model`

2021-11-23 14:26 UTC, dvelezroman commented on models/activities.js
> +  return activities;
same as above... singular `Activity`

2021-11-23 14:26 UTC, dvelezroman commented on seeders/20211123062651-activities.js
> +          deletedAt: new Date
`deleteAt` no va aqui en seeder. estas creando... 

cambiar por :

`name: 'Richard',
            content: 'test0',
           image: 'https://www.designevo.com/res/templates/thumb_small/colorful-hand-and-warm-community.png',
            createdAt: new Date(),
            updatedAt: new Date()`

2021-11-23 22:12 UTC, joselo85 commented on models/activities.js
> +  class activities extends Model {
En linea de lo que dice dvelezroman, el nombre de este archivo tambien deberia ser en singular, asi quedan todos iguales.

2021-11-24 02:52 UTC, dvelezroman approved these changes
Muy buen PR

2021-11-24 12:01 UTC, gabodmc commented on models/activity.js
> +      // define association here
Estaría faltando definir la asociación con el modelo de User

2021-11-24 12:58 UTC, joselo85 commented on models/activity.js
> +      // define association here
Coincido

2021-11-24 13:11 UTC, maxicuyo94 approved these changes

2021-11-24 13:51 UTC, gabyMangoni commented on migrations/20211123051718-create-activity.js
> +};
tendrias q dejar una linea debajo en blanco

2021-11-24 13:51 UTC, gabyMangoni commented on models/activity.js
> +};
tendrias q dejar una linea debajo en blanco

2021-11-24 13:51 UTC, gabyMangoni commented on seeders/20211123062651-create-activities.js
> +};
tendrias q dejar una linea debajo en blanco

2021-11-24 16:04 UTC, dvelezroman requested changes

2021-11-24 16:04 UTC, dvelezroman commented on models/activity.js
> +    modelName: 'Activity',
falta lo de paranoid y los otros configs... revisar los otros PRs ...

2021-11-24 18:11 UTC, dvelezroman approved these changes
Cool

2021-11-24 21:23 UTC, gabyMangoni approved these changes

2021-11-24 21:23 UTC, gabyMangoni commented on migrations/20211123051718-create-activity.js
> +};
Despues de la linea 26 tendrias que agregar 

,
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }

2021-11-24 21:23 UTC, gabyMangoni commented on models/activity.js
> +  });
Dentro del sequelize de la lineas 26 ademas del modelName, te faltan agregar algunos datos

 {
    sequelize,
    modelName: 'Activity',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    deletedAt: 'deletedAt',
    paranoid: true,
    timestamps: true
  });

2021-11-24 21:28 UTC, merged