[ENDPOINT] UPDATE/activities - OT102 - 67
alkemyTech/OT102-Server pull request #52
Opened 2021-12-01 03:01 UTC by Gabriiel99

**Description**
AS admin user
I WANT to update an existing activity
TO keep information up to date

**Criteria of acceptance:**
PUT / activities /: id - You must validate that the activity exists based on the id sent by parameter. In the event that there is no return an error, otherwise update it and return it with the updated data

2021-12-01 13:25 UTC, dvelezroman requested changes

2021-12-01 13:25 UTC, dvelezroman commented on routes/activities.js
> +router.put('/:id', isAdmin, update)
falta el middleware para validar los paramtros

2021-12-01 14:02 UTC, gabodmc requested changes

2021-12-01 14:02 UTC, gabodmc commented on services/activities.js
> +      throw new ErrorObject('activity not found with that ID', 404)
Fijate de cambiarle al nuevo handler `throw Error('activity not found with that ID', 404)`

2021-12-01 18:54 UTC, dvelezroman commented on routes/activities.js
> +router.put('/:id', [isAdmin, validateRequest(activitySchema)], update)
good

2021-12-01 18:55 UTC, dvelezroman approved these changes

2021-12-01 21:31 UTC, gabodmc approved these changes

2021-12-02 01:11 UTC, gabyMangoni approved these changes
Ok

2021-12-02 13:52 UTC, JonatanGarbuyo requested changes

2021-12-02 13:52 UTC, JonatanGarbuyo commented on routes/activities.js
>  router.get('/:id', getActivity)
falta el 
router.get('/', get)

se perdio' en los merges?

2021-12-02 13:52 UTC, JonatanGarbuyo commented on services/activities.js
> +    if (error.message === 'ID not found.') {
el if no va a coincidir porque el mensaje de error es distinto.  trae el id.

                 throw Error(`ID ${id} not found.`)
if (error.message === 'ID not found.') {

2021-12-02 15:05 UTC, gabyMangoni commented on routes/activities.js
>  router.get('/:id', getActivity)
esta en la linea 12..

2021-12-02 22:01 UTC, dvelezroman approved these changes

2021-12-03 12:27 UTC, JonatanGarbuyo approved these changes

2021-12-03 18:38 UTC, merged