[ENDPOINT] PUT /news/:id OT102-56
alkemyTech/OT102-Server pull request #53
Opened 2021-12-01 13:29 UTC by maxicuyo94

HOW: Admin user
I WANT: Update an existing novelty
TO: Keep content up to date

Acceptance criteria: PUT / news /: id - You must validate that the news exists based on the id sent by parameter. In the event that there is no return an error, otherwise update the news and return it with the updated data

2021-12-01 18:57 UTC, dvelezroman requested changes

2021-12-01 18:57 UTC, dvelezroman commented on routes/entries.js
> +router.put('/:id', isAdmin, updatedEntry)
falta esquema de validacion de parametros para esta request

2021-12-02 13:32 UTC, JonatanGarbuyo commented on services/entry.js
> +      400,
aca seria 500. server error
(400 es bad request)

2021-12-02 13:40 UTC, JonatanGarbuyo commented on services/entry.js
> +      `Error while updating entry: ${err.message}`,
acá tiras un 404 pero luego lo cambias a 400.

te faltaría un if  dentro del catch para el 404

fijate como esta hecho el de category  ;)

2021-12-02 13:46 UTC, JonatanGarbuyo commented on controllers/entry.js
> +      const updatedEntry = await getById(entryId, newEntry)
aca es  updateById.

2021-12-02 17:37 UTC, JonatanGarbuyo approved these changes

2021-12-02 18:24 UTC, gabyMangoni approved these changes
Ok

2021-12-02 21:00 UTC, dvelezroman approved these changes
excellent

2021-12-02 21:08 UTC, dvelezroman approved these changes
Excellente

2021-12-03 21:21 UTC, merged