[HELPER] sendMail (sendgrid)  Ot102-29
alkemyTech/OT102-Server pull request #54
Opened 2021-12-01 20:51 UTC by maxicuyo94

Description
HOW: user
I WANT: to be notified via email
TO: make sure certain events occurred

Acceptance criteria: Emails will be sent in different situations (when completing the Contact Form, registering on the site, etc.). To do this, you need to create a service that allows you to send them. We will use the sendgrid API.
Initially, the tasks are:

Install library that allows sending emails using sendgrid

Create a method that receives an email address as a parameter and sends to it.

2021-12-01 21:13 UTC, dvelezroman requested changes

2021-12-01 21:13 UTC, dvelezroman commented on helpers/index.js
> +    await sgMail.send(msg)
Aqui hay que crear una funcion que reciba un template HTML para enviar como cuerpo del correo

2021-12-03 16:19 UTC, gabodmc approved these changes

2021-12-03 20:18 UTC, dvelezroman approved these changes
cool

2021-12-03 22:01 UTC, joselo85 approved these changes

2021-12-03 22:02 UTC, merged