[ENDPOINT]  Activities [FIX]
alkemyTech/OT102-Server pull request #56
Opened 2021-12-03 15:49 UTC by JonatanGarbuyo

## Description
fix and unified criteria for errors and data response.

2021-12-03 15:58 UTC, dvelezroman commented on controllers/activities.js
> +  getAllActivities,
bien

2021-12-03 15:59 UTC, dvelezroman requested changes

2021-12-03 15:59 UTC, dvelezroman commented on routes/activities.js
> +router.get('/:id', isAdmin, getActivity)
no creo que necesite ser admin para obtener las actividades... ya que estas van a mostrarse en la pagina al publico y el detalle de cada una tambien...

2021-12-03 16:00 UTC, dvelezroman commented
solo un comentario (consulta)

2021-12-03 16:52 UTC, JonatanGarbuyo commented on routes/activities.js
> +router.get('/:id', isAdmin, getActivity)
Entonces esta mal la tarjeta?

[OT102-123](https://alkemy-labs.atlassian.net/browse/OT102-123)

2021-12-05 01:26 UTC, dvelezroman commented on routes/activities.js
> +router.get('/:id', isAdmin, getActivity)
solo pide listar .... no usa el middleware para admin.. las actividades tambien seran traidas por la pagina como usuario publico para mostrarlas

2021-12-05 01:27 UTC, dvelezroman requested changes
un comentario

2021-12-06 22:08 UTC, dvelezroman approved these changes
solo quitar el middleware de admin a la ruta y listo

2021-12-07 13:50 UTC, joselo85 approved these changes

2021-12-07 14:15 UTC, gabyMangoni approved these changes
All Ok

2021-12-07 15:16 UTC, merged