Ot102 30 Create migration and Slides model
alkemyTech/OT102-Server pull request #6
Opened 2021-11-23 14:15 UTC by maxicuyo94

Description
HOW TO: admin user
I WANT: to manage images
TO: efficiently modify visual content

Acceptance criteria: The slides on the home screen will be dynamically managed by the site administrator. They will have as fields imageUrl, text, order and organizationId (as they will belong to an ngo).

2021-11-23 14:34 UTC, dvelezroman requested changes
Buen Pr... corregir y arreglar el PR la descripcion y algo del codigo del model

2021-11-23 14:34 UTC, dvelezroman commented on migrations/20211123134047-create-slide.js
> +        type: Sequelize.STRING,
deberia ser mas bien de tipo TEXT

2021-11-23 14:34 UTC, dvelezroman commented on models/slide.js
> +      // organizationId: {
si no se usa .. borrar

2021-11-23 14:34 UTC, dvelezroman commented on models/slide.js
> +      modelName: 'Slide',
completar con las configuraciones que coloque en otrs PRs ... en el #3

2021-11-23 15:12 UTC, maxicuyo94 commented on migrations/20211123134047-create-slide.js
> +        type: Sequelize.STRING,
cambiado

2021-11-23 15:12 UTC, maxicuyo94 commented on models/slide.js
> +      // organizationId: {
eliminado

2021-11-23 15:13 UTC, maxicuyo94 commented on models/slide.js
> +      modelName: 'Slide',
agregado createdAt updatedAt deletedAt y paranoid

2021-11-23 16:47 UTC, JonatanGarbuyo approved these changes

2021-11-24 02:53 UTC, dvelezroman approved these changes
Excelent

2021-11-24 12:22 UTC, gabodmc approved these changes

2021-11-25 04:08 UTC, merged