[WIP][ENDPOINT] USER UPDATE OT102-127
alkemyTech/OT102-Server pull request #66
Opened 2021-12-17 02:33 UTC by maxicuyo94

COMO: Usuario
QUIERO: Editar mi perfil
PARA: Modificar mis datos personales cuando lo requiera

Criterios de aceptación: El usuario podrá editar su nombre, apellido, email y dispondrá
https://alkemy-labs.atlassian.net/browse/OT102-127

2021-12-17 19:51 UTC, gabyMangoni approved these changes

2021-12-17 21:24 UTC, dvelezroman commented on services/user.js
> +    throw createHttpError(err.statusCode || 500, err.message)
excelente

2021-12-17 21:24 UTC, dvelezroman approved these changes
buen PR

2021-12-17 21:25 UTC, JonatanGarbuyo requested changes

2021-12-17 21:25 UTC, JonatanGarbuyo commented on routes/user.js
> +router.put('/:id', destroy)
destroy?

2021-12-17 21:25 UTC, dvelezroman commented on routes/user.js
> +router.put('/:id', destroy)
update

2021-12-17 21:25 UTC, gabodmc approved these changes

2021-12-19 17:34 UTC, joselo85 approved these changes

2021-12-21 12:50 UTC, alexiscjscab approved these changes

2021-12-21 21:40 UTC, JonatanGarbuyo approved these changes

2021-12-21 21:40 UTC, merged