[WIP] [TESTS] ENDPOINTS /testimonials
alkemyTech/OT102-Server pull request #72
Opened 2021-12-24 22:35 UTC by joselo85

2021-12-27 20:04 UTC, JonatanGarbuyo commented on test/testimonials.test.js
> +      )
solo te falto comprobar que el testimonial que pediste con GET
tenga el mismo contenido que el que creado al principio.  ;)

2021-12-27 20:10 UTC, JonatanGarbuyo requested changes
esta muy bien. 
solo unos pequeños cambios

2021-12-27 20:10 UTC, JonatanGarbuyo commented on test/testimonials.test.js
> +    it('Returns Status code 500 with non existing ID', async () => {
debe responder 404.
en todo caso arregla' el endpoint.

2021-12-27 20:10 UTC, JonatanGarbuyo commented on test/testimonials.test.js
> +      await deleteTestimonialPermanently(id)
este delete seria mejor que este dentro de un afterEach()
si falla el  expect, el borrado  no se ejecuta correctamente.

2021-12-27 21:17 UTC, gabyMangoni approved these changes

2021-12-27 21:18 UTC, gabodmc approved these changes

2021-12-27 21:20 UTC, JonatanGarbuyo approved these changes

2021-12-27 21:32 UTC, alexiscjscab approved these changes

2021-12-29 00:16 UTC, dvelezroman approved these changes

2021-12-29 00:16 UTC, merged