[ENTRY]: migration - model  - OT102-40
alkemyTech/OT102-Server pull request #8
Opened 2021-11-23 14:53 UTC by joselo85

# Description:
***
AS: administrator user
I WANT: to manage "Novedades" (News)
TO:  manage the content.
 
## Acceptance Criteria:
***
Entries will be the content published under the "Novedades"(News) section of the website. Table name: entries. Fields : name, content, image, categoryId, type (one entry may be an event, news, etc), deletedAt (used for softDelete).

***
## How to reproduce this change:
Create Model:
`sequelize model:generate --name Entry --attributes name:string,content:text,image:string,categoryId:integer,type:string,deletedAt:date`
Apply migration:
`npx sequelize-cli db:migrate`

Undo migration:
`npx sequelize-cli db:migrate:undo:all --to XXXXXXXXXXXXXX-nombre-migracion.js`
***
## Evidence:

![OT102-40](https://user-images.githubusercontent.com/74208929/143047072-f4975df6-ac15-4fd6-ad6c-b48cd4df791b.png)

2021-11-23 15:41 UTC, dvelezroman requested changes
Perfecto, solo un pequeno comment

2021-11-23 15:41 UTC, dvelezroman commented on migrations/20211123135111-create-entry.js
> +          model: 'Categories',
revisar si es en plural o con el nombre original en singular.. esta asociacion...

2021-11-23 16:05 UTC, joselo85 commented on migrations/20211123135111-create-entry.js
> +          model: 'Categories',
Segun otros proyectos, y tomando como ejemplo el archivo migrations/20200921211634-create-user.js veo que todos usan el plural.

2021-11-23 16:06 UTC, gabodmc requested changes

2021-11-23 16:06 UTC, gabodmc commented on models/entry.js
> +      User.belongsTo(models.Categoy, { as: 'category' });
Te falto una "r" en la asociación... seria models.Category

2021-11-24 02:54 UTC, dvelezroman commented on migrations/20211123135111-create-entry.js
> +          model: 'Categories',
ok

2021-11-24 02:54 UTC, dvelezroman approved these changes
Excelente

2021-11-24 12:25 UTC, gabodmc approved these changes

2021-11-24 12:53 UTC, joselo85 commented on models/entry.js
> +      User.belongsTo(models.Categoy, { as: 'category' });
Solucionado! Gracias!

2021-11-24 12:53 UTC, joselo85 commented on models/entry.js
> +      User.belongsTo(models.Categoy, { as: 'category' });
Solucionado! Gracias!

2021-11-24 13:14 UTC, maxicuyo94 approved these changes

2021-11-24 14:16 UTC, gabyMangoni commented on models/entry.js
> +    },
deletedAt figura en la linea 21 y en la 28, ya figura abajo dentro de sequelize, creeria que solo tenes que dejar el de la 28

2021-11-24 14:39 UTC, JonatanGarbuyo approved these changes

2021-11-24 14:39 UTC, JonatanGarbuyo commented on models/entry.js
> +      name: DataTypes.STRING,
¿los atributos de la clase deberían tener las mismas opciones que en la migración?

ej:   name:  allowNull: false,

2021-11-24 14:39 UTC, JonatanGarbuyo commented on models/entry.js
> +    },
Gaby. fijate que línea 21 es la inicialización de los atributos de la clase y la línea 28 es una referencia.
El de la línea 28 es el que nos pidió agregar Darío.

2021-11-24 14:45 UTC, joselo85 commented on models/entry.js
> +      name: DataTypes.STRING,
Yo me base en laos modelos de usuario y la migracion de usuario como ejemplo. Ahi solo pone las restricciones en el archivo de migrations

2021-11-24 14:48 UTC, joselo85 commented on models/entry.js
> +    },
En las lineas 25  a 28 tienen como objetivo explicitar como se van a llamar las columnas en nuesta base de datos. Podrias transformar todos al modo underscore:true, o hacer uno por uno como hicimos nosotros de pasar uno a uno.

2021-11-24 15:10 UTC, merged

2021-11-24 15:14 UTC, gabyMangoni commented on models/entry.js
> +    },
Si.. pero con dejar solo el de la linea 28 funciona... no es necesario dejar el de la 21.