[ORGANIZATION]migration - model - OT102-12
alkemyTech/OT102-Server pull request #9
Opened 2021-11-23 17:42 UTC by cheaguz

### **DESCRIPTION** : 
As: Developer
I want: Link Testimonials with API
To: Show content dynamically

### Acceptance criteria :
 GET request to route / organizations / 1 / public

The endpoint should return a JSON with the name, image, phone, address and welcomeText fields
### Evidence
![Sin título](https://user-images.githubusercontent.com/67702629/143076309-b528a960-8085-4dce-b8c4-9439240f8973.png)

2021-11-23 18:34 UTC, JonatanGarbuyo approved these changes

2021-11-23 21:09 UTC, joselo85 approved these changes

2021-11-23 21:11 UTC, joselo85 commented
Me parece que deberias cambiar el titulo del PR, ya que se trata de un endpoint y no de una migracion y modelo de DB.

2021-11-24 03:00 UTC, dvelezroman commented on routes/organizationsRouter.js
> +      res.status(200).send(response);
vamos a usar json(response)

2021-11-24 03:02 UTC, dvelezroman requested changes
Esta bien la logica.. solo hay que refactorizar para seguir el formato arqutectura:

RUTA => CONTROLADOR => SERVICIO => MODELO

puedes guiarte con la ruta que existe ahi para /ping y para /users

ademas existe un manejador de errores que tambien ya hay ejemplo de como fue usado para las rutas que estan de guia en la carpetas controller....

2021-11-24 03:02 UTC, dvelezroman commented on test/organizations.test.js
> +describe('GET /organizations/1/public', () => {
buenisimo...

2021-11-24 03:02 UTC, dvelezroman commented on routes/organizationsRouter.js
> +        data,
esto hay que revisar como esta en unos modelos hechos...

2021-11-24 18:13 UTC, dvelezroman requested changes

2021-11-24 18:13 UTC, dvelezroman commented on app.js
> +app.use('/organizations', organizationRouter);
revisar la configuracion de las rutas con la arquitectura en el repo...  parece que no tiene actualizado esta branch con develop... please do a 
`git merge origin/develop`

2021-11-24 18:15 UTC, dvelezroman commented
Hay muchos archivos cambiados... debes primero actualizar con develop... luego solo subir los que cambiaste o creaste... hay 27 archivos en este PR.... por favor revisar

2021-11-25 15:03 UTC, dvelezroman requested changes

2021-11-25 15:03 UTC, dvelezroman commented on routes/organizationsRouter.js
> +    res.status(500).send({ status: false, data: Error, msg: 'Something was wrong!' });
revisar error handler

2021-11-25 15:03 UTC, dvelezroman commented on app.js
> +app.use('/organizations', organizationRouter)
no iria esto aqui. sino en routes/index.js

2021-11-25 15:03 UTC, dvelezroman commented on controllers/organizationsController.js
> +      const response = {
cambiar con el helper de response

2021-11-25 15:03 UTC, dvelezroman commented on controllers/organizationsController.js
> +      next(error)
actualizar con el helper para error

2021-11-25 15:10 UTC, dvelezroman commented
Quedo con danios l PR

2021-11-25 15:10 UTC, closed without merging